apiVersion: v1
kind: Service
metadata:
  name: posts-nodeport-svc
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      port: 4000
      protocol: TCP
      targetPort: 4000
